// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ1etVwkK46i0LXUHKapMEr-oZdyRVneo',
    appId: '1:121988994607:web:f62f0e7dbd8758b2bd18da',
    messagingSenderId: '121988994607',
    projectId: 'bookhub-8e48c',
    authDomain: 'bookhub-8e48c.firebaseapp.com',
    storageBucket: 'bookhub-8e48c.appspot.com',
    measurementId: 'G-VWKQWL16JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR4thSSXIok_U0mYAnys-diaecUEpmueI',
    appId: '1:121988994607:android:0f5660bc7ebb8e30bd18da',
    messagingSenderId: '121988994607',
    projectId: 'bookhub-8e48c',
    storageBucket: 'bookhub-8e48c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApoN0DirW4Sf6_TVheLHNXKy1Le_4t0pk',
    appId: '1:121988994607:ios:594962b29a68bd61bd18da',
    messagingSenderId: '121988994607',
    projectId: 'bookhub-8e48c',
    storageBucket: 'bookhub-8e48c.appspot.com',
    iosBundleId: 'com.example.androidAppProjectBookhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApoN0DirW4Sf6_TVheLHNXKy1Le_4t0pk',
    appId: '1:121988994607:ios:b158f4515fc7f444bd18da',
    messagingSenderId: '121988994607',
    projectId: 'bookhub-8e48c',
    storageBucket: 'bookhub-8e48c.appspot.com',
    iosBundleId: 'com.example.androidAppProjectBookhub.RunnerTests',
  );
}
