// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qU3f878Aapmv8Tt8gjo5GRZ3K74f2oE',
    appId: '1:278297422991:web:3090f14e83bb319435d4fa',
    messagingSenderId: '278297422991',
    projectId: 'bookhub-7a6bc',
    authDomain: 'bookhub-7a6bc.firebaseapp.com',
    storageBucket: 'bookhub-7a6bc.appspot.com',
    measurementId: 'G-LPG2Q7W8ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFHUY1PW6q_1WDeRxqfuaLNrr0W3ea14A',
    appId: '1:278297422991:android:6ea97758d554d35e35d4fa',
    messagingSenderId: '278297422991',
    projectId: 'bookhub-7a6bc',
    storageBucket: 'bookhub-7a6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPZGkuHUOfAgNyvMIId7UQz8UgkJPA62g',
    appId: '1:278297422991:ios:029fb0dd7f3717c535d4fa',
    messagingSenderId: '278297422991',
    projectId: 'bookhub-7a6bc',
    storageBucket: 'bookhub-7a6bc.appspot.com',
    iosBundleId: 'com.example.androidAppProjectBookhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPZGkuHUOfAgNyvMIId7UQz8UgkJPA62g',
    appId: '1:278297422991:ios:029fb0dd7f3717c535d4fa',
    messagingSenderId: '278297422991',
    projectId: 'bookhub-7a6bc',
    storageBucket: 'bookhub-7a6bc.appspot.com',
    iosBundleId: 'com.example.androidAppProjectBookhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qU3f878Aapmv8Tt8gjo5GRZ3K74f2oE',
    appId: '1:278297422991:web:6b6cb477684d96ee35d4fa',
    messagingSenderId: '278297422991',
    projectId: 'bookhub-7a6bc',
    authDomain: 'bookhub-7a6bc.firebaseapp.com',
    storageBucket: 'bookhub-7a6bc.appspot.com',
    measurementId: 'G-479GL04DMS',
  );

}